apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-ebs-csi-driver
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/aws-ebs-csi-driver
    chart: aws-ebs-csi-driver
    targetRevision: "2.12.0"       
    helm:
      values: |-
        controller:
          serviceAccount:
            create: true
            name: ebs-csi-controller-sa
            annotations:
              eks.amazonaws.com/role-arn: arn:aws:iam::266735804784:role/AmazonEKS_EBS_CSI_Driver_IRSA
                                         
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
