apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/elastic/helm-charts.git
    targetRevision: main
    path: elasticsearch        # <-- community chart의 디렉터리
    helm:
      values: |
        replicas: 1
        minimumMasterNodes: 1
        esConfig:
          elasticsearch.yml: |
            node.store.allow_mmap: false
            xpack.security.enabled: false

        ## ─── dev: 경량화 (리소스 낮춤) ─────────────────────
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi

        ## ─── persistence 설정 (dev: 용량 축소) ─────────────
        persistence:
          enabled: true
          storageClass: ebs-sc      # 클러스터에 존재하는 SC 이름
          size: 10Gi             # dev용 축소 용량


  destination:
    server: https://kubernetes.default.svc
    namespace: elk-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
