apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metricbeat-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co  # <-- Helm repo
    chart: metricbeat                 # <-- Helm chart name
    targetRevision: 8.5.1             # <-- 이미지와 일치하는 버전
    helm:
      values: |
        imageTag: 8.5.1
        daemonset:
          enabled: true
        deployment:
          enabled: false

        ## dev: 경량화 (리소스 낮춤)
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi

        metricbeatConfig:
          metricbeat.yml: |
            metricbeat.modules:
              - module: system
                metricsets:
                  - cpu
                  - memory
                  - network
                  - filesystem
                period: 10s
            output.elasticsearch:
              hosts: ["https://elasticsearch-master.elk-dev.svc:9200"]
              username: "elastic"
              password: "changeme1234"
              ssl:
                enabled: true
                verification_mode: none

  destination:
    server: https://kubernetes.default.svc
    namespace: elk-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
