apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://github.com/100-hours-a-week/21-iceT-gitops
    targetRevision: main
    path: apps/base/spring
    helm:
      valueFiles:
      - ../../../env/dev/values-dev.yaml
      releaseName: spring-dev
  destination:
    server: https://kubernetes.default.svc
    namespace: spring-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
